#!/bin/bash

# Configuration des flags d'erreurs pour bash
set -o errexit
set -o pipefail
set -o nounset


python << END_PYTHON
    import sys
    import time
    import psycopg2

    suggest_unrecoverable_after = 30
    start = time.time()

    while True:
        try:
            psycopg2.connect(
                dbname="${POSTGRES_DB}",
                user="${POSTGRES_USER}",
                password="${POSTGRES_PASSWORD}",
                host="${POSTGRES_HOSTS}",
                port="${POSTGRES_PORT}",
            )
            break
        except psycopg2.OperationalError as error:
            sys.stderr.write('Waiting for PostgreSQL...\n')
            if time.time() - start > suggest_unrecoverable_after:
                sys.stderr.write(" This is taking longer than expected. The following exception may be indicative of an unrecoverable error: f'{error}'\n")

        time.sleep(1)
END_PYTHON
}



>&2 echo 'PostgreSQL is available'

# Exécution du fichier /start reçu en paramètre
exec "$@"