# Generated by Django 4.1.2 on 2022-12-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('web_project', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True)),
                ('items_list', models.CharField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('keywords_list', models.CharField(blank=True, max_length=256)),
                ('url_github_oc', models.URLField(blank=True, null=True)),
                ('url_github_portfolio', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('related_project_name', models.CharField(blank=True, max_length=128)),
                ('related_project_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category')),
            ],
        ),
    ]
