# Generated by Django 4.1.2 on 2022-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web_app',
            field=models.BooleanField(default=True),
        ),
    ]
