# Generated by Django 4.1.2 on 2022-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_web_app_category_web_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='items_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
