# Generated by Django 4.1.2 on 2022-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_items_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='oc_project',
            field=models.BooleanField(default=False),
        ),
    ]
