# Generated by Django 4.1.2 on 2022-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_oc_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='oc_project',
        ),
        migrations.AddField(
            model_name='project',
            name='related_project_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='related_project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='items_list',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
