version: "3"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ./portfolio/.env
    ports:
      - 25432:5432
    volumes:
      - drf_vue_portfolio_postgres:/var/lib/postgresql/data

volumes:
  drf_vue_portfolio_postgres: {}


