version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: portfolio_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./portfolio/.env
    ports:
      - 8000:8000
    command: /start

  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ./portfolio/.env
    # ports:
    #   - 25432:5432
    volumes:
      - drf_vue_portfolio_postgres:/var/lib/postgresql/data

volumes:
  drf_vue_portfolio_postgres: {}


